language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
- platformio platform install espressif8266 --with-package tool-mkspiffs
script:
- platformio --version
- platformio run 
- platformio run -t buildfs